// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID   int64       `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Dob  pgtype.Date `db:"dob" json:"dob"`
}
